-- ==========================================
-- Supabase Schema for KBT Application
-- Paste this script into your Supabase SQL Editor
-- ==========================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'player',
    email VARCHAR(255),
    university VARCHAR(255),
    is_blocked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. QUESTIONS TABLE
CREATE TABLE IF NOT EXISTS public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    options JSONB NOT NULL,
    answer TEXT NOT NULL,
    topic VARCHAR(100),
    difficulty VARCHAR(20) DEFAULT 'medium',
    type VARCHAR(20) DEFAULT 'mcq',
    keywords TEXT,
    image_url TEXT,
    year_category VARCHAR(20) DEFAULT '1st',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. LEADERBOARD TABLE
CREATE TABLE IF NOT EXISTS public.leaderboard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL REFERENCES public.users(username) ON DELETE CASCADE,
    score NUMERIC(10, 2) NOT NULL,
    time_taken INTEGER NOT NULL,
    year VARCHAR(10) DEFAULT '1st',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT leaderboard_username_unique UNIQUE (username)
);

-- 4. EVENT SETTINGS TABLE
CREATE TABLE IF NOT EXISTS public.event_settings (
    id INTEGER PRIMARY KEY DEFAULT 1,
    is_active BOOLEAN DEFAULT FALSE,
    end_time TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure default event settings record exists
INSERT INTO public.event_settings (id, is_active)
VALUES (1, FALSE)
ON CONFLICT (id) DO NOTHING;

-- 5. ROW LEVEL SECURITY (RLS)
-- If accessing via API routes with SUPABASE_SERVICE_ROLE_KEY, RLS is automatically bypassed.
-- The policies below enable safe read access for anon client if needed.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_settings ENABLE ROW LEVEL SECURITY;

-- Allow public read access to leaderboard and event status
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'leaderboard' AND policyname = 'Allow public read access to leaderboard') THEN
        CREATE POLICY "Allow public read access to leaderboard" ON public.leaderboard FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'event_settings' AND policyname = 'Allow public read access to event_settings') THEN
        CREATE POLICY "Allow public read access to event_settings" ON public.event_settings FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'questions' AND policyname = 'Allow public read access to questions') THEN
        CREATE POLICY "Allow public read access to questions" ON public.questions FOR SELECT USING (true);
    END IF;
END $$;

-- 6. SEED INITIAL QUESTIONS (Optional sample data)
INSERT INTO public.questions (text, options, answer, topic, difficulty, type, year_category)
VALUES 
('Which of the following is NOT a built-in React Hook?', '["useState", "useEffect", "useFetch", "useContext"]'::jsonb, 'useFetch', 'React', 'easy', 'mcq', '1st'),
('What is the output of 2 + ''2'' in JavaScript?', '["4", "22", "NaN", "Error"]'::jsonb, '22', 'JavaScript', 'easy', 'mcq', '1st'),
('Which CSS property is used to change the text color of an element?', '["font-color", "text-color", "color", "foreground-color"]'::jsonb, 'color', 'CSS', 'easy', 'mcq', '1st'),
('What does SQL stand for?', '["Structured Query Language", "Stylesheet Query Language", "Statement Question Language", "Structured Question List"]'::jsonb, 'Structured Query Language', 'Databases', 'medium', 'mcq', '1st'),
('Which HTTP method is typically used to update a resource?', '["GET", "POST", "PUT", "DELETE"]'::jsonb, 'PUT', 'Networking', 'easy', 'mcq', '1st')
ON CONFLICT DO NOTHING;

